[project]
requires-python = ">=3.12"

[tool.basedpyright]
reportConstantRedefinition = false # See https://github.com/microsoft/pyright/issues/5265
reportUnusedCallResult = false

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM",
    "D100",
    "D101",
    "D103",
    "D105",
    "D107",
    "FBT001",
    "G004",
    "ISC003",
    "TRY003"
]
